<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shaunenoch" failures="4" tests="27" name="runner.TestRunner" time="96.125" errors="1" timestamp="2023-12-07T22:31:51 EST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="5.007"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="6.845"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.570"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.285"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.532"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.182">
    <failure message="expected [U are logged in] but found [Invalid Username and Password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [U are logged in] but found [Invalid Username and Password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps_DsAlgo.LoginSteps.user_stays_on_the_login_page(LoginSteps.java:182)
at ✽.user stays on the login page(file:///C:/Users/shaun/eclipse-workspace/Ds_AlgoProject3/src/test/resources/FeaturesDsAlgo/ALogin.feature:47)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.629"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.313"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.915"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.680"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.319"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.625"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.809">
    <failure message="expected [Welcome to Queue] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome to Queue] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps_DsAlgo.QueueSteps.user_should_get_a_error_message(QueueSteps.java:134)
at ✽.user should get a error message(file:///C:/Users/shaun/eclipse-workspace/Ds_AlgoProject3/src/test/resources/FeaturesDsAlgo/Queue.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.578"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.118"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.094"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.530"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="10.952">
    <error message="Sheet index (-1) is out of range (0..0)" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Sheet index (-1) is out of range (0..0)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetIndex(XSSFWorkbook.java:1484)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetAt(XSSFWorkbook.java:1186)
at Utilities.ExcelReader.getCellData(ExcelReader.java:55)
at Steps_DsAlgo.LoginSteps.user_enters_invalid_data_from_and_in_excelpath(LoginSteps.java:40)
at ✽.user enters invalid data from "Register" and 2 in excelpath(file:///C:/Users/shaun/eclipse-workspace/Ds_AlgoProject3/src/test/resources/FeaturesDsAlgo/ALogin.feature:6)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.268"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="8.835"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.656"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.582"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.039">
    <failure message="expected [] but found [Overview of Trees]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [Overview of Trees]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps_DsAlgo.TreeSteps.user_checks_for_the_error_message(TreeSteps.java:84)
at ✽.user checks for the error message(file:///C:/Users/shaun/eclipse-workspace/Ds_AlgoProject3/src/test/resources/FeaturesDsAlgo/FTree.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.518">
    <failure message="expected [Welcome to Graph] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome to Graph] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps_DsAlgo.GraphSteps.user_should_have_error_message(GraphSteps.java:133)
at ✽.user should have error message(file:///C:/Users/shaun/eclipse-workspace/Ds_AlgoProject3/src/test/resources/FeaturesDsAlgo/Graph.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="5.323"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.402"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="2.519"/>
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
